### ISSUE TITLE
controllerAs

### ISSUE THREAD

**Issue by HuyPhat** [christianalfoni/flux-angular#61] opened 2016-04-11 07:30 UTC
Is it possible to use 'this' with your flux-angular? I face with an issue while avoid using $scope to bind model to view

**Comment by jrust** [comment] 2016-04-11 15:25
It's certainly possible, and would be good as a path forward to angluar 2.  All it's doing is setting up a listener to a Baobab cursor.  There's nothing in the `$listenTo` method that actually relies on `$scope` except garbage collection. So if we can figure out another way to get listeners destroyed when the controller is destroyed it would work.  Another alternative is that I could just expose a `$listenTo` on the `flux` service and the user would then be in charge of their own GC.  Any ideas welcome as well as more info on what the problem is for you with scope?

**Comment by jrust** [comment] 2016-11-07 18:06
We now also rely on $scope for evalAsync so closing this because it is currently central to the architecture.

**Closed by jrust** 2016-11-07 18:06 UTC
Labels: enhancement, question
